### PR TITLE
break main.cc

### PR DESCRIPTION
**Pull request by MHCooke**
ensure merge is blocked when CI fails

### CODE REVIEW

**Review by Jambls — APPROVED** [review]

**Review by bear-in-the-air — APPROVED** [review]
see if it breaks

**Comment by MHCooke** [comment]
image
oh dear, need to fix that

**Comment by MHCooke** [comment]
There we go, figured out how to mark them as required. I've chosen static analysis, formatting and unit tests (since unit tests passing requires build to pass too). Should I just turn them all on, or leave it as is?

**Comment by bear-in-the-air** [comment]
> 

Those make sense to me, We just want all CI to pass before merge is allowed.

**Comment by MHCooke** [comment]
Have verified that bad code cannot be merged

**Pull request closed without merging**
