### PR TITLE
Put content into readme (#35)

### PR DESCRIPTION
**Pull request by MHCooke**

### CODE REVIEW

**Comment by Jambls** [comment]
Once you've got the social media, it looks good to me

**Review by Jambls — APPROVED** [review]

**Comment by MHCooke** [comment]
Demo is visible here:

https://github.com/daft-engineers/vocoder/tree/update_readme

**Comment by bear-in-the-air** [comment]
Did you decide to not bother to explain how to run the static analysis and clang format or is that extraneous?

**Comment by MHCooke** [comment]
> Did you decide to not bother to explain how to run the static analysis and clang format or is that extraneous?

Good point, I'll add a section for that

**Review by bear-in-the-air — APPROVED** [review]

**Pull request merged**
